const defaults=[
 {id:1,title:'Canon EOS 1500D',price:24500,category:'Electronics',location:'Chennai',condition:'Good',emoji:'📷',tint:'#dfe8e8',description:'Camera body with two batteries and a 18–55mm lens.',seller:'Ananya'},
 {id:2,title:'Solid wood desk',price:4200,category:'Furniture',location:'Bengaluru',condition:'Good',emoji:'🪑',tint:'#eee2d5',description:'Sturdy desk with two drawers. Pickup only.',seller:'Rahul'},
 {id:3,title:'Royal Enfield helmet',price:1800,category:'Vehicles',location:'Chennai',condition:'Like new',emoji:'🪖',tint:'#e5e2dc',description:'Worn just a few times. Size M.',seller:'Vikram'},
 {id:4,title:'Kindle Paperwhite',price:6800,category:'Electronics',location:'Mumbai',condition:'Good',emoji:'📖',tint:'#e3e7dc',description:'10th generation, 8GB, includes charging cable.',seller:'Meera'},
 {id:5,title:'Leather backpack',price:1200,category:'Fashion',location:'Bengaluru',condition:'Fair',emoji:'🎒',tint:'#e8ded5',description:'Comfortable daily backpack with plenty of life left.',seller:'Sana'},
 {id:6,title:'Atomic Habits',price:250,category:'Books',location:'Chennai',condition:'Good',emoji:'📚',tint:'#e8e1ca',description:'Clean copy with no markings.',seller:'Arun'},
 {id:7,title:'Floor lamp',price:1500,category:'Furniture',location:'Mumbai',condition:'Like new',emoji:'💡',tint:'#dfdfd8',description:'Warm white lamp, perfect for reading corners.',seller:'Ishaan'},
 {id:8,title:'Vintage denim jacket',price:900,category:'Fashion',location:'Chennai',condition:'Good',emoji:'🧥',tint:'#dce6ed',description:'Classic medium-wash denim. Size L.',seller:'Nila'}];
const $=s=>document.querySelector(s),page=document.body.dataset.page,money=n=>'₹'+Number(n).toLocaleString('en-IN'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=JSON.parse(localStorage.getItem('secondhand-items')||'null')||defaults,saved=new Set(JSON.parse(localStorage.getItem('secondhand-saved')||'[]')),threads=JSON.parse(localStorage.getItem('secondhand-threads')||'{}');
function persist(){localStorage.setItem('secondhand-items',JSON.stringify(items));localStorage.setItem('secondhand-saved',JSON.stringify([...saved]));localStorage.setItem('secondhand-threads',JSON.stringify(threads))}function counts(){document.querySelectorAll('[data-saved-count]').forEach(x=>x.textContent=saved.size);document.querySelectorAll('[data-item-count]').forEach(x=>x.textContent=items.length)}
function card(x,mine=false){return `<article class="card"><a href="product.html?id=${x.id}"><div class="art" style="--tint:${x.tint}">${x.emoji}</div></a><button class="heart ${saved.has(x.id)?'saved':''}" data-save="${x.id}">${saved.has(x.id)?'♥':'♡'}</button><div class="card-info"><a href="product.html?id=${x.id}" class="card-link"><div class="price">${money(x.price)}</div><div class="title">${esc(x.title)}</div><div class="meta">${esc(x.location)} · ${esc(x.condition)}</div></a>${mine?`<button class="delete" data-delete="${x.id}">Remove listing</button>`:''}</div></article>`}
function bindCards(container){container.onclick=e=>{let id=Number(e.target.dataset.save||e.target.dataset.delete);if(e.target.dataset.save){saved.has(id)?saved.delete(id):saved.add(id);persist();init()}if(e.target.dataset.delete){items=items.filter(x=>x.id!==id);saved.delete(id);persist();init()}}}
function home(){let category='All',renderCategories=()=>{let cats=['All',...new Set(items.map(x=>x.category))];$('#categories').innerHTML=cats.map(x=>`<button class="${x===category?'active':''}" data-category="${x}">${x}</button>`).join('')},render=()=>{let q=$('#search').value.toLowerCase(),loc=$('#location').value,sort=$('#sort').value,list=items.filter(x=>(category==='All'||x.category===category)&&(loc==='All locations'||x.location===loc)&&(`${x.title} ${x.description}`).toLowerCase().includes(q));list.sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.id-a.id);$('#products').innerHTML=list.map(card).join('');$('#resultText').textContent=`${list.length} listing${list.length===1?'':'s'} available`;$('#empty').hidden=!!list.length;bindCards($('#products'))};renderCategories();render();$('#search').oninput=render;$('#location').onchange=render;$('#sort').onchange=render;$('#categories').onclick=e=>{if(e.target.dataset.category){category=e.target.dataset.category;renderCategories();render()}}}
function product(){let id=Number(new URLSearchParams(location.search).get('id')),x=items.find(i=>i.id===id);if(!x){$('#productDetail').innerHTML='<p class="empty">This listing has wandered off.</p>';return}$('#productDetail').innerHTML=`<section class="detail"><div class="detail-art" style="--tint:${x.tint}">${x.emoji}</div><div class="detail-info"><div class="meta">${esc(x.location)} · ${esc(x.category)}</div><h1>${esc(x.title)}</h1><div class="detail-price">${money(x.price)}</div><span class="condition">${esc(x.condition)}</span><p>${esc(x.description)}</p><p class="meta">Listed by ${esc(x.seller||'You')}</p><div class="detail-actions"><a class="sell" href="messages.html?item=${x.id}">Message seller</a><button class="secondary" id="saveItem">${saved.has(id)?'♥ Saved':'♡ Save item'}</button></div></div></section>`;$('#saveItem').onclick=()=>{saved.has(id)?saved.delete(id):saved.add(id);persist();counts();product()}}
function sell(){let f=$('#sellForm');f.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f));items.unshift({id:Date.now(),...d,price:+d.price,emoji:'📦',tint:'#e7e5dc',seller:'You'});persist();location.href='profile.html'}}
function savedPage(){let list=items.filter(x=>saved.has(x.id));$('#products').innerHTML=list.map(card).join('');$('#resultText').textContent=`${list.length} saved item${list.length===1?'':'s'}`;$('#empty').hidden=!!list.length;bindCards($('#products'))}
function profile(){let list=items.filter(x=>x.seller==='You');$('#myProducts').innerHTML=list.map(x=>card(x,true)).join('');$('#empty').hidden=!!list.length;bindCards($('#myProducts'))}
function messages(){let pre=Number(new URLSearchParams(location.search).get('item')),active=pre||Number(Object.keys(threads)[0]);if(pre&&!threads[pre]){let x=items.find(i=>i.id===pre);if(x)threads[pre]=[{from:'seller',text:`Hi! Yes, the ${x.title} is available.`}]}function draw(){let keys=Object.keys(threads);$('#threadList').innerHTML=keys.length?keys.map(id=>{let x=items.find(i=>i.id===Number(id));return `<button class="thread ${Number(id)===active?'active':''}" data-thread="${id}">${esc(x?.title||'Listing')}</button>`}).join(''):'<p class="muted">No conversations yet.</p>';let x=items.find(i=>i.id===active);if(!x){$('#messages').innerHTML='';$('#messageForm').hidden=true;return}$('#conversationHead').innerHTML=`<h2>${esc(x.seller||'Seller')}</h2><p class="muted">About ${esc(x.title)}</p>`;$('#messages').innerHTML=threads[active].map(m=>`<div class="bubble ${m.from==='me'?'me':''}">${esc(m.text)}</div>`).join('');$('#messageForm').hidden=false;$('#messages').scrollTop=9999}$('#threadList').onclick=e=>{if(e.target.dataset.thread){active=Number(e.target.dataset.thread);draw()}};$('#messageForm').onsubmit=e=>{e.preventDefault();let input=$('#messageInput');if(!input.value.trim())return;threads[active].push({from:'me',text:input.value});input.value='';persist();draw()};persist();draw()}
function init(){counts();if(page==='home')home();if(page==='product')product();if(page==='sell')sell();if(page==='saved')savedPage();if(page==='profile')profile();if(page==='messages')messages()}init();
